### ISSUE TITLE
Support void of invoice and payments

### ISSUE THREAD

**Issue by geoffcorey** [apigrate/quickbooks#10]
Currently the library does not support void. The fix is easy by overriding the operation based on opts. See Quickbook docs

operation=void for invoices
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice#void-an-invoice

include=void for payment
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/payment#void-a-payment

Pull request to fix https://github.com/apigrate/quickbooks/pull/9

**Comment by geoffcorey** [comment]
bumpity

**Comment by geoffcorey** [comment]
crickets

**Comment by gaumeister** [comment]
Hi @geoffcorey, I also left a comment on your pull request. Please take a look at the `void-impl` branch and let me know if it meets your needs. Intuit isn't consistent with their support of voids on every entity, so I had to implement it slightly differently than you suggested.

**Comment by geoffcorey** [comment]
I think your changes should work.   I will try and pull and run local to confirm today or monday

**Comment by geoffcorey** [comment]
Tested it out and it looks good!  Thank you!

**Comment by gaumeister** [comment]
Released v4.3.0

**Comment by geoffcorey** [comment]
Thank you!
